export const ABRIR_MODAL = 'ABRIR_MODAL';
export const CERRAR_MODAL = 'CERRAR_MODAL';
export const ABRIR_REGISTRARSE = 'ABRIR_REGISTRARSE';
export const CERRAR_REGISTRARSE = 'CERRAR_REGISTRARSE';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const ENTRAR_CRUD_USUARIOS = 'ENTRAR_CRUD_USUARIOS';
export const ABRIR_AGREGAR_USUARIOS = 'ABRIR_AGREGAR_USUARIOS';
export const CERRAR_AGREGAR_USUARIOS = 'CERRAR_AGREGAR_USUARIOS';

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const COMENZAR_DESCARGA_USUARIOS = 'COMENZAR_DESCARGA_USUARIOS';
export const DESCARGA_USUARIOS_EXITO = 'DESCARGA_USUARIOS_EXITO';
export const DESCARGA_USUARIOS_ERROR = 'DESCARGA_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINADO_EXITO = 'USUARIO_ELIMINADO_EXITO';
export const USUARIO_ELIMINADO_ERROR = 'USUARIO_ELIMINADO_ERROR';

export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const USUARIO_EDITADO_EXITO = 'USUARIO_EDITADO_EXITO';
export const USUARIO_EDITADO_ERROR = 'USUARIO_EDITADO_ERROR';

export const ESTA_LOGUEADO = 'ESTA_LOGUEADO';
export const NO_ESTA_LOGUEADO = 'NO_ESTA_LOGUEADO';

export const CERRAR_SESION = 'CERRAR_SESION';
export const ROL_USUARIO = 'ROL_USUARIO';