export const ABRIR_MODAL = 'ABRIR_MODAL';
export const CERRAR_MODAL = 'CERRAR_MODAL';
export const ABRIR_REGISTRARSE = 'ABRIR_REGISTRARSE';
export const CERRAR_REGISTRARSE = 'CERRAR_REGISTRARSE';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const ENTRAR_CRUD_USUARIOS = 'ENTRAR_CRUD_USUARIOS';
export const ABRIR_AGREGAR_USUARIOS = 'ABRIR_AGREGAR_USUARIOS';
export const CERRAR_AGREGAR_USUARIOS = 'CERRAR_AGREGAR_USUARIOS';

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const COMENZAR_DESCARGA_USUARIOS = 'COMENZAR_DESCARGA_USUARIOS';
export const DESCARGA_USUARIOS_EXITO = 'DESCARGA_USUARIOS_EXITO';
export const DESCARGA_USUARIOS_ERROR = 'DESCARGA_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINADO_EXITO = 'USUARIO_ELIMINADO_EXITO';
export const USUARIO_ELIMINADO_ERROR = 'USUARIO_ELIMINADO_ERROR';

export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const USUARIO_EDITADO_EXITO = 'USUARIO_EDITADO_EXITO';
export const USUARIO_EDITADO_ERROR = 'USUARIO_EDITADO_ERROR';

export const ESTA_LOGUEADO = 'ESTA_LOGUEADO';
export const NO_ESTA_LOGUEADO = 'NO_ESTA_LOGUEADO';
export const CERRAR_SESION = 'CERRAR_SESION';
export const ROL_USUARIO = 'ROL_USUARIO';

export const ABRIR_PERFIL = 'ABRIR_PERFIL';
export const CERRAR_PERFIL = 'CERRAR_PERFIL';
export const ACTUALIZADO_PERFIL = 'ACTUALIZADO_PERFIL';
export const ACTUALIZADO_PERFIL_ERROR = 'ACTUALIZADO_PERFIL_ERROR';

export const ENTRAR_CRUD_MENU = 'ENTRAR_CRUD_MENU';
export const ENTRAR_CRUD_CATEGORIA = 'ENTRAR_CRUD_CATEGORIA';
export const ENTRAR_CRUD_INSUMOS = 'ENTRAR_CRUD_INSUMOS';

export const ABRIR_AGREGAR_CATEGORIA = 'ABRIR_AGREGAR_CATEGORIA';
export const CERRAR_AGREGAR_CATEGORIA = 'CERRAR_AGREGAR_CATEGORIA';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const AGREGAR_CATEGORIA_EXITO = 'AGREGAR_CATEGORIA_EXITO';
export const AGREGAR_CATEGORIA_ERROR = 'AGREGAR_CATEGORIA_ERROR';

export const COMENZAR_DESCARGA_CATEGORIA = 'COMENZAR_DESCARGA_CATEGORIA';
export const DESCARGA_CATEGORIA_EXITO = 'DESCARGA_CATEGORIA_EXITO';
export const DESCARGA_CATEGORIA_ERROR = 'DESCARGA_CATEGORIA_ERROR';

export const OBTENER_CATEGORIA_ELIMINAR = 'OBTENER_CATEGORIA_ELIMINAR';
export const CATEGORIA_ELIMINADO_EXITO = 'CATEGORIA_ELIMINADO_EXITO';
export const CATEGORIA_ELIMINADO_ERROR = 'CATEGORIA_ELIMINADO_ERROR';

export const OBTENER_CATEGORIA_EDITAR = 'OBTENER_CATEGORIA_EDITAR';
export const CATEGORIA_EDITADO_EXITO = 'CATEGORIA_EDITADO_EXITO';
export const CATEGORIA_EDITADO_ERROR = 'CATEGORIA_EDITADO_ERROR';

export const ABRIR_AGREGAR_MENU = 'ABRIR_AGREGAR_MENU';
export const CERRAR_AGREGAR_MENU = 'CERRAR_AGREGAR_MENU';

export const AGREGAR_MENU = 'AGREGAR_MENU';
export const AGREGAR_MENU_EXITO = 'AGREGAR_MENU_EXITO';
export const AGREGAR_MENU_ERROR = 'AGREGAR_MENU_ERROR';
export const AGREGAR_MENU_ERRORES = 'AGREGAR_MENU_ERRORES';

export const COMENZAR_DESCARGA_MENU = 'COMENZAR_DESCARGA_MENU';
export const DESCARGA_MENU_EXITO = 'DESCARGA_MENU_EXITO';
export const DESCARGA_MENU_ERROR = 'DESCARGA_MENU_ERROR';

export const OBTENER_MENU_ELIMINAR = 'OBTENER_MENU_ELIMINAR';
export const MENU_ELIMINADO_EXITO = 'MENU_ELIMINADO_EXITO';
export const MENU_ELIMINADO_ERROR = 'MENU_ELIMINADO_ERROR';

export const OBTENER_MENU_EDITAR = 'OBTENER_MENU_EDITAR';
export const MENU_EDITADO_EXITO = 'MENU_EDITADO_EXITO';
export const MENU_EDITADO_ERROR = 'MENU_EDITADO_ERROR';
export const MENU_EDITADO_ERRORES = 'MENU_EDITADO_ERRORES';

export const PAGINA_MENUES_FILTRADOS = 'PAGINA_MENUES_FILTRADOS';