export const ABRIR_MODAL = 'ABRIR_MODAL';
export const CERRAR_MODAL = 'CERRAR_MODAL';
export const ABRIR_REGISTRARSE = 'ABRIR_REGISTRARSE';
export const CERRAR_REGISTRARSE = 'CERRAR_REGISTRARSE';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const ENTRAR_CRUD_USUARIOS = 'ENTRAR_CRUD_USUARIOS';
export const ABRIR_AGREGAR_USUARIOS = 'ABRIR_AGREGAR_USUARIOS';
export const CERRAR_AGREGAR_USUARIOS = 'CERRAR_AGREGAR_USUARIOS';

export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

export const COMENZAR_DESCARGA_USUARIOS = 'COMENZAR_DESCARGA_USUARIOS';
export const DESCARGA_USUARIOS_EXITO = 'DESCARGA_USUARIOS_EXITO';
export const DESCARGA_USUARIOS_ERROR = 'DESCARGA_USUARIOS_ERROR';

export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINADO_EXITO = 'USUARIO_ELIMINADO_EXITO';
export const USUARIO_ELIMINADO_ERROR = 'USUARIO_ELIMINADO_ERROR';

export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const USUARIO_EDITADO_EXITO = 'USUARIO_EDITADO_EXITO';
export const USUARIO_EDITADO_ERROR = 'USUARIO_EDITADO_ERROR';

export const DESCARGA_USER_ID = 'DESCARGA_USER_ID';

export const ESTA_LOGUEADO = 'ESTA_LOGUEADO';
export const NO_ESTA_LOGUEADO = 'NO_ESTA_LOGUEADO';
export const CERRAR_SESION = 'CERRAR_SESION';
export const ROL_USUARIO = 'ROL_USUARIO';

export const ABRIR_PERFIL = 'ABRIR_PERFIL';
export const CERRAR_PERFIL = 'CERRAR_PERFIL';
export const ACTUALIZADO_PERFIL = 'ACTUALIZADO_PERFIL';
export const ACTUALIZADO_PERFIL_ERROR = 'ACTUALIZADO_PERFIL_ERROR';

export const ENTRAR_CRUD_MENU = 'ENTRAR_CRUD_MENU';
export const ENTRAR_CRUD_CATEGORIA = 'ENTRAR_CRUD_CATEGORIA';
export const ENTRAR_CRUD_INSUMOS = 'ENTRAR_CRUD_INSUMOS';
export const ENTRAR_CRUD_CATEGORIA_INSUMOS = 'ENTRAR_CRUD_CATEGORIA_INSUMOS';
export const ENTRAR_CRUD_PEDIDOS = 'ENTRAR_CRUD_PEDIDOS';
export const ENTRAR_CRUD_CONFIGURACION = 'ENTRAR_CRUD_CONFIGURACION';

export const ABRIR_AGREGAR_CATEGORIA = 'ABRIR_AGREGAR_CATEGORIA';
export const CERRAR_AGREGAR_CATEGORIA = 'CERRAR_AGREGAR_CATEGORIA';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const AGREGAR_CATEGORIA_EXITO = 'AGREGAR_CATEGORIA_EXITO';
export const AGREGAR_CATEGORIA_ERROR = 'AGREGAR_CATEGORIA_ERROR';
export const AGREGAR_CATEGORIA_ERRORES = 'AGREGAR_CATEGORIA_ERRORES';

export const COMENZAR_DESCARGA_CATEGORIA = 'COMENZAR_DESCARGA_CATEGORIA';
export const DESCARGA_CATEGORIA_EXITO = 'DESCARGA_CATEGORIA_EXITO';
export const DESCARGA_CATEGORIA_ERROR = 'DESCARGA_CATEGORIA_ERROR';
export const DESCARGA_LISTADO_CATEGORIA = 'DESCARGA_LISTADO_CATEGORIA';

export const OBTENER_CATEGORIA_ELIMINAR = 'OBTENER_CATEGORIA_ELIMINAR';
export const CATEGORIA_ELIMINADO_EXITO = 'CATEGORIA_ELIMINADO_EXITO';
export const CATEGORIA_ELIMINADO_ERROR = 'CATEGORIA_ELIMINADO_ERROR';

export const OBTENER_CATEGORIA_EDITAR = 'OBTENER_CATEGORIA_EDITAR';
export const CATEGORIA_EDITADO_EXITO = 'CATEGORIA_EDITADO_EXITO';
export const CATEGORIA_EDITADO_ERROR = 'CATEGORIA_EDITADO_ERROR';
export const CATEGORIA_EDITADO_ERRORES = 'CATEGORIA_EDITADO_ERRORES';

export const ABRIR_AGREGAR_MENU = 'ABRIR_AGREGAR_MENU';
export const CERRAR_AGREGAR_MENU = 'CERRAR_AGREGAR_MENU';

export const AGREGAR_MENU = 'AGREGAR_MENU';
export const AGREGAR_MENU_EXITO = 'AGREGAR_MENU_EXITO';
export const AGREGAR_MENU_ERROR = 'AGREGAR_MENU_ERROR';
export const AGREGAR_MENU_ERRORES = 'AGREGAR_MENU_ERRORES';

export const COMENZAR_DESCARGA_MENU = 'COMENZAR_DESCARGA_MENU';
export const DESCARGA_MENU_EXITO = 'DESCARGA_MENU_EXITO';
export const DESCARGA_MENU_ERROR = 'DESCARGA_MENU_ERROR';

export const OBTENER_MENU_ELIMINAR = 'OBTENER_MENU_ELIMINAR';
export const MENU_ELIMINADO_EXITO = 'MENU_ELIMINADO_EXITO';
export const MENU_ELIMINADO_ERROR = 'MENU_ELIMINADO_ERROR';

export const OBTENER_MENU_EDITAR = 'OBTENER_MENU_EDITAR';
export const MENU_EDITADO_EXITO = 'MENU_EDITADO_EXITO';
export const MENU_EDITADO_ERROR = 'MENU_EDITADO_ERROR';
export const MENU_EDITADO_ERRORES = 'MENU_EDITADO_ERRORES';

export const PAGINA_MENUES_FILTRADOS = 'PAGINA_MENUES_FILTRADOS';
export const PAGINA_CATALOGO_INSUMOS_PADRES = 'PAGINA_CATALOGO_INSUMOS_PADRES';
export const ABRIR_DETALLE_MENU = 'ABRIR_DETALLE_MENU';
export const CERRAR_DETALLE_MENU = 'CERRAR_DETALLE_MENU';
export const OBTENER_MENU = 'OBTENER_MENU';
export const OBTENER_MENU_ERROR = 'OBTENER_MENU_ERROR';

export const ABRIR_AGREGAR_CATEGORIA_INSUMO = 'ABRIR_AGREGAR_CATEGORIA_INSUMO';
export const CERRAR_AGREGAR_CATEGORIA_INSUMO = 'CERRAR_AGREGAR_CATEGORIA_INSUMO';

export const AGREGAR_CATEGORIA_INSUMO = 'AGREGAR_CATEGORIA_INSUMO';
export const AGREGAR_CATEGORIA_INSUMO_EXITO = 'AGREGAR_CATEGORIA_INSUMO_EXITO';
export const AGREGAR_CATEGORIA_INSUMO_ERRORES = 'AGREGAR_CATEGORIA_INSUMO_ERRORES';
export const AGREGAR_CATEGORIA_INSUMO_ERROR = 'AGREGAR_CATEGORIA_INSUMO_ERROR';

export const COMENZAR_DESCARGA_CATEGORIA_INSUMO = 'COMENZAR_DESCARGA_CATEGORIA_INSUMO';
export const DESCARGA_CATEGORIA_INSUMO_EXITO = 'DESCARGA_CATEGORIA_INSUMO_EXITO';
export const DESCARGA_CATEGORIA_INSUMO_ERROR = 'DESCARGA_CATEGORIA_INSUMO_ERROR';
export const DESCARGA_LISTADO_CATEGORIA_INSUMO = 'DESCARGA_LISTADO_CATEGORIA_INSUMO';
export const DESCARGA_LISTADO_CATEGORIA_INSUMO_ABUELO = 'DESCARGA_LISTADO_CATEGORIA_INSUMO_ABUELO';
export const DESCARGA_LISTADO_CATEGORIA_INSUMO_PADRE = 'DESCARGA_LISTADO_CATEGORIA_INSUMO_PADRE';
export const DESCARGA_LISTADO_CATEGORIA_INSUMO_HIJO = 'DESCARGA_LISTADO_CATEGORIA_INSUMO_HIJO';
export const DESCARGA_LISTADO_MENUS = 'DESCARGA_LISTADO_MENUS';
export const DESCARGA_LISTADO_INSUMOS = 'DESCARGA_LISTADO_INSUMOS';

export const OBTENER_CATEGORIA_INSUMO_ELIMINAR = 'OBTENER_CATEGORIA_INSUMO_ELIMINAR';
export const CATEGORIA_INSUMO_ELIMINADO_EXITO = 'CATEGORIA_INSUMO_ELIMINADO_EXITO';
export const CATEGORIA_INSUMO_ELIMINADO_ERROR = 'CATEGORIA_INSUMO_ELIMINADO_ERROR';

export const OBTENER_CATEGORIA_INSUMO_EDITAR = 'OBTENER_CATEGORIA_INSUMO_EDITAR';
export const CATEGORIA_INSUMO_EDITADO_EXITO = 'CATEGORIA_INSUMO_EDITADO_EXITO';
export const CATEGORIA_INSUMO_EDITADO_ERROR = 'CATEGORIA_INSUMO_EDITADO_ERROR';
export const CATEGORIA_INSUMO_EDITADO_ERRORES = 'CATEGORIA_INSUMO_EDITADO_ERRORES';

export const ABRIR_AGREGAR_INSUMO = 'ABRIR_AGREGAR_INSUMO';
export const CERRAR_AGREGAR_INSUMO = 'CERRAR_AGREGAR_INSUMO';

export const AGREGAR_INSUMO = 'AGREGAR_INSUMO';
export const AGREGAR_INSUMO_EXITO = 'AGREGAR_INSUMO_EXITO';
export const AGREGAR_INSUMO_ERRORES = 'AGREGAR_INSUMO_ERRORES';
export const AGREGAR_INSUMO_ERROR = 'AGREGAR_INSUMO_ERROR';

export const COMENZAR_DESCARGA_INSUMO = 'COMENZAR_DESCARGA_INSUMO';
export const DESCARGA_INSUMO_EXITO = 'DESCARGA_INSUMO_EXITO';
export const DESCARGA_INSUMO_ERROR = 'DESCARGA_INSUMO_ERROR';

export const OBTENER_INSUMO_ELIMINAR = 'OBTENER_INSUMO_ELIMINAR';
export const INSUMO_ELIMINADO_EXITO = 'INSUMO_ELIMINADO_EXITO';
export const INSUMO_ELIMINADO_ERROR = 'INSUMO_ELIMINADO_ERROR';

export const OBTENER_INSUMO_EDITAR = 'OBTENER_INSUMO_EDITAR';
export const INSUMO_EDITADO_EXITO = 'INSUMO_EDITADO_EXITO';
export const INSUMO_EDITADO_ERROR = 'INSUMO_EDITADO_ERROR';
export const INSUMO_EDITADO_ERRORES = 'INSUMO_EDITADO_ERRORES';

export const GUARDAR_CATEGORIA_INSUMO_PADRE = 'GUARDAR_CATEGORIA_INSUMO_PADRE';
export const PAGINA_MENUES_INSUMO_FILTRADOS = 'PAGINA_MENUES_INSUMO_FILTRADOS';
export const OBTENER_INSUMO = 'OBTENER_INSUMO';

export const ABRIR_CARRITO = 'ABRIR_CARRITO';
export const CERRAR_CARRITO = 'CERRAR_CARRITO';

export const AGREGAR_CARRITO = 'AGREGAR_CARRITO';
export const AGREGAR_CARRITO_EXITO = 'AGREGAR_CARRITO_EXITO';
export const AGREGAR_CARRITO_ERROR = 'AGREGAR_CARRITO_ERROR';

export const OBTENER_PRODUCTO_CARRITO_ELIMINAR = 'OBTENER_PRODUCTO_CARRITO_ELIMINAR';
export const PRODUCTO_CARRITO_ELIMINADO_EXITO = 'PRODUCTO_CARRITO_ELIMINADO_EXITO';
export const ELIMINAR_PRODUCTO_CARRITO_ERROR = 'ELIMINAR_PRODUCTO_CARRITO_ERROR';

export const OBTENER_PRODUCTO_CARRITO = 'OBTENER_PRODUCTO_CARRITO';

export const AGREGAR_ORDEN = 'AGREGAR_ORDEN';
export const AGREGAR_ORDEN_EXITO = 'AGREGAR_ORDEN_EXITO';
export const AGREGAR_ORDEN_ERROR = 'AGREGAR_ORDEN_ERROR';

export const COMENZAR_DESCARGA_PEDIDOS = 'COMENZAR_DESCARGA_PEDIDOS';
export const DESCARGA_PEDIDOS_EXITO = 'DESCARGA_PEDIDOS_EXITO';
export const DESCARGA_PEDIDOS_ERROR = 'DESCARGA_PEDIDOS_ERROR';

export const DESCARGA_LISTADO_MENU_DETALLE = 'DESCARGA_LISTADO_MENU_DETALLE';
export const DESCARGA_MENU_DETALLE_ERROR = 'DESCARGA_MENU_DETALLE_ERROR';
export const OBTENER_MENU_DETALLE_EDITAR = 'OBTENER_MENU_DETALLE_EDITAR';

export const ABRIR_MODAL_DETALLE_PEDIDO = 'ABRIR_MODAL_DETALLE_PEDIDO';
export const CERRAR_MODAL_DETALLE_PEDIDO = 'CERRAR_MODAL_DETALLE_PEDIDO';
export const GUARDAR_PRODUCTO_MENU_DETALLEPEDIDO = 'GUARDAR_PRODUCTO_MENU_DETALLEPEDIDO';

export const OBTENER_INSUMO_POR_ID = 'OBTENER_INSUMO_POR_ID';
export const OBTENER_INSUMO_POR_ID_ERROR = 'OBTENER_INSUMO_POR_ID_ERROR';

export const OBTENER_MENU_POR_ID = 'OBTENER_MENU_POR_ID';
export const OBTENER_MENU_POR_ID_ERROR = 'OBTENER_MENU_POR_ID_ERROR';
export const GUARDA_DETALLE_PEDIDO = 'GUARDA_DETALLE_PEDIDO';

export const CONFIGURACION_EDITADO_EXITO = 'CONFIGURACION_EDITADO_EXITO';
export const CONFIGURACION_EDITADO_ERROR = 'CONFIGURACION_EDITADO_ERROR';
export const DESCARGA_LISTADO_CONFIGURACION = 'DESCARGA_LISTADO_CONFIGURACION';
export const OBTENER_CONFIGURACION_ERROR = 'OBTENER_CONFIGURACION_ERROR';

export const ORDEN_EDITAR = 'ORDEN_EDITAR';
export const ORDEN_EDITADO_EXITO = 'ORDEN_EDITADO_EXITO';
export const ORDEN_EDITADO_ERRORES = 'ORDEN_EDITADO_ERRORES';
export const ORDEN_EDITADO_ERROR = 'ORDEN_EDITADO_ERROR';
